# Generated by Django 2.0.5 on 2018-08-10 09:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opponent_grid', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[(' ', ' '), ('.', '.'), ('i', 'i'), ('x', 'x'), ('o', 'o')], default=' ', max_length=1), size=10), size=10)),
                ('game_status', models.CharField(choices=[('IN_PROGRESS', 'IN_PROGRESS'), ('FINISHED', 'FINISHED')], default='IN_PROGRESS', max_length=50)),
            ],
        ),
    ]
