# Generated by Django 2.0.5 on 2018-08-09 12:12

import battleship_game.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opponent_grid', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[(battleship_game.models.GameCell(' '), ' '), (battleship_game.models.GameCell('.'), '.'), (battleship_game.models.GameCell('i'), 'i'), (battleship_game.models.GameCell('x'), 'x'), (battleship_game.models.GameCell('o'), 'o')], default=battleship_game.models.GameCell(' '), max_length=1), size=10), size=10)),
                ('game_status', models.CharField(choices=[(battleship_game.models.GameStatus('IN_PROGRESS'), 'IN_PROGRESS'), (battleship_game.models.GameStatus('FINISHED'), 'FINISHED')], default=battleship_game.models.GameStatus('IN_PROGRESS'), max_length=20)),
            ],
        ),
    ]
